//TeXeR source: https://artofproblemsolving.com/texer/rpwsynlp
// Generated by ggb_to_asy.py
// Edit source: https://www.geogebra.org/calculator/bfsmcpxt

// Set up canvas with unit size
unitsize(4 cm);

// Define line style for mirrors
pen thick = linewidth(2.0bp);

// Declare vertices of retroreflector
pair A, B, C;

// Define retroreflector geometry: two mirrors meeting at apex
A = (0, 0);      // apex point where mirrors meet
B = (-1, -1);    // left mirror endpoint
C = (1, -1);     // right mirror endpoint

// Draw the two mirror surfaces
draw(A--B, thick);  // left mirror
draw(A--C, thick);  // right mirror

// Label the mirror surfaces
label("mirror", (-0.5, -0.5), NW);  // left mirror label
label("mirror", (0.5, -0.5), NE);   // right mirror label